# frozen_string_literal: true

require "seafoam/version"
require "seafoam/binary/io_binary_reader"
require "seafoam/bgv/bgv_parser"
require "seafoam/colors"
require "seafoam/graph"
require "seafoam/graal/graph_description"
require "seafoam/graal/source"
require "seafoam/graal/pi"
require "seafoam/passes"
require "seafoam/passes/truffle_translators/translators"
require "seafoam/passes/truffle"
require "seafoam/passes/graal"
require "seafoam/passes/fallback"
require "seafoam/spotlight"
require "seafoam/isabelle_writer"
require "seafoam/json_writer"
require "seafoam/graphviz_writer"
require "seafoam/mermaid_writer"
require "seafoam/markdown_writer"
require "seafoam/commands"
require "seafoam/formatters/formatters"
